### ISSUE TITLE
Rewrite address bar

### ISSUE THREAD

**Issue by veso266** [classilla/overbitenx#14]
Hi there is it possible to rewrite browsers address bar to show gopher address, as now (for gopher://khzae.net) it shows something wierd: moz-extension://bda9ab2c-eeeb-418f-acaa-0a2b990e2222/d?gopher%3A%2F%2Fkhzae.net

**Comment by classilla** [comment]
No. There is no WebExtension API to allow that, so it's not possible, unfortunately.
