### ISSUE TITLE
Gopherpedia articles with spaces in titles render incorrectly

### ISSUE THREAD

**Issue by Aicaya** [classilla/overbitenx#5]
Still new to gopher sites in general so I don't know if it applies to more, but in the case of Gopherpedia, if an article has a space in it then it will throw a lot of errors and generally not render properly (articles with only one word in the title render fine). Pages render correctly on other browsers such as lynx and gopherus, so it's not an issue with the site.

Compare: 
`gopher://gopherpedia.com/0/Wendigo`
`gopher://gopherpedia.com/0/Hollow Knight`

Or just browse the site and play around a tad. Pattern holds.

If it helps, the links display correctly in the Floodgap proxy via OverbiteWX. Only difference I can see is that it uses the actual space character instead of %20, but the link in lynx and gopherus has %20 instead of the space character so that shouldn't be a factor. I think.

**Comment by classilla** [comment]
I can reproduce. Looks like we're failing to deURL escape the selector. The actual transmitted request is `gopherpedia.com/Hollow%20Knight`, not `gopherpedia.com/Hollow Knight`, so this likely indicates a front-end Jasper issue. Thanks for the report.

**Comment by classilla** [comment]
Oh, and as a polite request: if you make any future bug reports, please include what you see in the Browser Console. In this case, the encoded request was there, so that made finding the actual problem much simpler.

**Comment by classilla** [comment]
Pushed to AMO
